/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniide;

/**
 *
 * @author luislocon
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jarbolproyecto = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanelworkspace = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jbtprojectformat = new javax.swing.JButton();
        jbtfileformat = new javax.swing.JButton();
        jtabplus = new javax.swing.JTabbedPane();
        jmainmenu = new javax.swing.JMenuBar();
        jmi_archivo = new javax.swing.JMenu();
        jmi_analisis = new javax.swing.JMenu();
        jmi_reportes = new javax.swing.JMenu();
        jmi_ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini - IDE");
        setName("jnameview"); // NOI18N

        jScrollPane1.setViewportView(jarbolproyecto);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jbtprojectformat.setText(">>");

        jbtfileformat.setText(">");

        javax.swing.GroupLayout jpanelworkspaceLayout = new javax.swing.GroupLayout(jpanelworkspace);
        jpanelworkspace.setLayout(jpanelworkspaceLayout);
        jpanelworkspaceLayout.setHorizontalGroup(
            jpanelworkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelworkspaceLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelworkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtfileformat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtprojectformat, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpanelworkspaceLayout.setVerticalGroup(
            jpanelworkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelworkspaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelworkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelworkspaceLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jbtfileformat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtprojectformat)
                .addGap(130, 130, 130))
        );

        jTabbedPane1.addTab("tab1", jpanelworkspace);
        jTabbedPane1.addTab("+", jtabplus);

        jmi_archivo.setText("Archivo");
        jmainmenu.add(jmi_archivo);

        jmi_analisis.setText("Analizar");
        jmainmenu.add(jmi_analisis);

        jmi_reportes.setText("Reportes");
        jmainmenu.add(jmi_reportes);

        jmi_ayuda.setText("Ayuda");
        jmainmenu.add(jmi_ayuda);

        setJMenuBar(jmainmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPane1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jarbolproyecto;
    private javax.swing.JButton jbtfileformat;
    private javax.swing.JButton jbtprojectformat;
    private javax.swing.JMenuBar jmainmenu;
    private javax.swing.JMenu jmi_analisis;
    private javax.swing.JMenu jmi_archivo;
    private javax.swing.JMenu jmi_ayuda;
    private javax.swing.JMenu jmi_reportes;
    private javax.swing.JPanel jpanelworkspace;
    private javax.swing.JTabbedPane jtabplus;
    // End of variables declaration//GEN-END:variables
}
